from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from pathlib import Path
from datetime import datetime

CHALLAN_DIR = Path(__file__).parent.parent.parent / "storage" / "challans"
CHALLAN_DIR.mkdir(parents=True, exist_ok=True)


def generate_challan(session) -> str:
    """
    Generate a PDF packing report (challan) for a completed session.
    session: SQLModel Session object
    Returns: file path to generated PDF
    """
    output_path = str(CHALLAN_DIR / f"{session.id}.pdf")
    doc = SimpleDocTemplate(
        output_path, pagesize=A4,
        leftMargin=2 * cm, rightMargin=2 * cm,
        topMargin=2 * cm, bottomMargin=2 * cm,
    )
    styles = getSampleStyleSheet()
    elements = []

    # Title
    elements.append(Paragraph("DECODERS — PACKING CHALLAN", styles["Title"]))
    elements.append(Spacer(1, 0.3 * cm))
    elements.append(Paragraph("Warehouse Box Count Record", styles["Heading2"]))
    elements.append(Spacer(1, 1 * cm))

    # Main data table
    stopped_str = (
        session.stopped_at.strftime("%d %b %Y, %H:%M:%S")
        if session.stopped_at else "—"
    )
    started_str = session.started_at.strftime("%d %b %Y, %H:%M:%S")

    data = [
        ["Field", "Value"],
        ["Session ID", f"#{session.id}"],
        ["Batch ID", session.batch_id],
        ["Operator ID", session.operator_id],
        ["Session Start", started_str],
        ["Session End", stopped_str],
        ["Final Box Count", str(session.final_box_count)],
        ["Input Mode", session.input_mode.title() if hasattr(session, 'input_mode') else "Live"],
        ["Video Reference", f"Session {session.id} — stored in system"],
        ["Generated On", datetime.utcnow().strftime("%d %b %Y, %H:%M UTC")],
    ]

    table = Table(data, colWidths=[7 * cm, 11 * cm])
    table.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), colors.HexColor("#0a0e1a")),
        ("TEXTCOLOR",     (0, 0), (-1, 0), colors.white),
        ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, 0), 11),
        ("BACKGROUND",    (0, 1), (0, -1), colors.HexColor("#f0f4f8")),
        ("FONTNAME",      (0, 1), (0, -1), "Helvetica-Bold"),
        ("GRID",          (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
        ("TOPPADDING",    (0, 0), (-1, -1), 9),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 9),
        ("LEFTPADDING",   (0, 0), (-1, -1), 10),
        # Highlight the box count row
        ("BACKGROUND",    (1, 6), (1, 6), colors.HexColor("#dcfce7")),
        ("FONTNAME",      (1, 6), (1, 6), "Helvetica-Bold"),
        ("FONTSIZE",      (1, 6), (1, 6), 14),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 1.5 * cm))
    elements.append(Paragraph(
        "Auto-generated by DECODERS Warehouse System. "
        "This document is a verified packing record.",
        styles["Normal"]
    ))

    doc.build(elements)
    return output_path
