from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from pathlib import Path
from datetime import datetime
import json

CHALLAN_DIR = Path(__file__).parent.parent.parent / "storage" / "challans"
CHALLAN_DIR.mkdir(parents=True, exist_ok=True)


def generate_challan(session) -> str:
    """
    Generate a PDF packing report (challan) for a completed session.
    session: SQLModel Session object
    Returns: file path to generated PDF
    """
    output_path = str(CHALLAN_DIR / f"{session.id}.pdf")
    doc = SimpleDocTemplate(
        output_path, pagesize=A4,
        leftMargin=2 * cm, rightMargin=2 * cm,
        topMargin=2 * cm, bottomMargin=2 * cm,
    )
    styles = getSampleStyleSheet()
    elements = []

    # Title
    elements.append(Paragraph("DECODERS — PACKING CHALLAN", styles["Title"]))
    elements.append(Spacer(1, 0.3 * cm))
    elements.append(Paragraph("Warehouse Box Count Record", styles["Heading2"]))
    elements.append(Spacer(1, 1 * cm))

    # Parse dynamic products list
    try:
        products = json.loads(session.products_json or "[]")
    except Exception:
        products = []
    total_qty = sum(int(p.get("qty", 0)) for p in products)
    pickup = session.pickup_date or "—"

    data = [
        ["Customer Detail", "", "Challan No.", session.challan_no or "—"],
        ["M/S", session.customer_ms or "—", "Pickup Date", pickup],
        ["Transporter ID", session.transporter_id or "—", "Lot No.", session.batch_id or "—"],
        ["Courier Partner", session.courier_partner or "—", "No. of Boxes", str(session.final_box_count)],
        ["", "", "", ""],
        ["Sr. No.", "Name of Product", "Qty", ""],
    ]
    for i, product in enumerate(products, start=1):
        data.append([f"{i}.", product.get("name", ""), str(product.get("qty", 0)), ""])
    data.append(["", "Total", str(total_qty), ""])

    # Calculate optimal column widths (A4 width is 21cm, minus 4cm margins = 17cm)
    table = Table(data, colWidths=[3.5 * cm, 5.5 * cm, 3.5 * cm, 4.5 * cm])
    
    # Row indices (0-based): header=0, MS=1, transporter=2, courier=3, blank=4, col-header=5, products=6..5+len, total=last
    product_header_row = 5
    total_row = 6 + len(products)

    style = TableStyle([
        # Base dark theme
        ("BACKGROUND",    (0, 0), (-1, -1), colors.HexColor("#1A1A1A")),
        ("TEXTCOLOR",     (0, 0), (-1, -1), colors.HexColor("#E5E5E5")),
        ("FONTNAME",      (0, 0), (-1, -1), "Helvetica"),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("PADDING",       (0, 0), (-1, -1), 10),
        ("GRID",          (0, 0), (-1, -1), 0.5, colors.HexColor("#555555")),
        # Spans
        ("SPAN",          (0, 0), (1, 0)),
        ("SPAN",          (0, 4), (3, 4)),
        # Bold headers
        ("FONTNAME",      (0, 0), (3, 0), "Helvetica-Bold"),
        ("FONTNAME",      (0, product_header_row), (-1, product_header_row), "Helvetica-Bold"),
        # Green No. of Boxes
        ("TEXTCOLOR",     (3, 3), (3, 3), colors.HexColor("#34D399")),
        ("FONTNAME",      (3, 3), (3, 3), "Helvetica-Bold"),
        # Total row
        ("FONTNAME",      (1, total_row), (2, total_row), "Helvetica-Bold"),
        ("TEXTCOLOR",     (2, total_row), (2, total_row), colors.HexColor("#34D399")),
    ])

    table.setStyle(style)
    elements.append(table)
    elements.append(Spacer(1, 1.5 * cm))
    elements.append(Paragraph(
        "Auto-generated by DECODERS Warehouse Vision System.",
        styles["Normal"]
    ))

    doc.build(elements)
    return output_path
