from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from pathlib import Path
from datetime import datetime

CHALLAN_DIR = Path(__file__).parent.parent.parent / "storage" / "challans"
CHALLAN_DIR.mkdir(parents=True, exist_ok=True)


def generate_challan(session) -> str:
    """
    Generate a PDF packing report (challan) for a completed session.
    session: SQLModel Session object
    Returns: file path to generated PDF
    """
    output_path = str(CHALLAN_DIR / f"{session.id}.pdf")
    doc = SimpleDocTemplate(output_path, pagesize=A4)
    styles = getSampleStyleSheet()
    elements = []

    # Title
    elements.append(Paragraph("PACKING CHALLAN", styles["Title"]))
    elements.append(Spacer(1, 0.5 * cm))
    elements.append(Paragraph("Warehouse Box Count Report", styles["Heading2"]))
    elements.append(Spacer(1, 1 * cm))

    # Main data table
    stopped_at_str = session.stopped_at.strftime("%Y-%m-%d %H:%M:%S") if session.stopped_at else "N/A"
    started_at_str = session.started_at.strftime("%Y-%m-%d %H:%M:%S")

    data = [
        ["Field", "Value"],
        ["Session ID", str(session.id)],
        ["Batch ID", session.batch_id],
        ["Operator ID", session.operator_id],
        ["Date & Time (Start)", started_at_str],
        ["Date & Time (End)", stopped_at_str],
        ["Final Box Count", str(session.final_box_count)],
        ["Video Reference", f"Session {session.id} — available via system API"],
        ["Report Generated", datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")],
    ]

    table = Table(data, colWidths=[7 * cm, 10 * cm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e3a5f")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 12),
        ("BACKGROUND", (0, 1), (0, -1), colors.HexColor("#f0f4f8")),
        ("FONTNAME", (0, 1), (0, -1), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f9f9f9")]),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 1 * cm))
    elements.append(Paragraph("This document was automatically generated by the PS2 Warehouse System.", styles["Normal"]))

    doc.build(elements)
    return output_path
